version: "2"
volumes:
  var_lib_go-server_addons:
  var_log_go-server:
  etc_go:
  go-addons:
  var_go:
services:
  gocd-server:
    image: gocd/gocd-server
    ports:
      - '8153:8153'
    volumes:
      - ./var/lib/go-server_addons:/var/lib/go-server/addons
      - ./var/log/go-server:/var/log/go-server
      - ./etc/go:/etc/go
      - ./go-addons:/go-addons
      - ./var/go:/var/go
  gocd-agent:
    image: gocd/gocd-agent
    environment:
      - GO_SERVER=gocd-server
    links:
      - gocd-server
